#!/usr/bin/env bash

VAULT=${HOME}/Vault

# find ${VAULT} \
#     \( -path '*/3. Review' -o -path '*/Daily Notes' -o -path '*/.git' -o -path '*/.obsidian' \) \
#     -prune \
#     -o \
#     -type f \
#     -name "*.md" \
#     -not -name ".*" \
#     -mtime -2 -print


N8N=${HOME}/n8n/review/input
mkdir -p $N8N
find ${VAULT} \( -path '*/3. Review' -o -path '*/Daily Notes' -o -path '*/.git' -o -path '*/.obsidian' \) -prune -o -type f -name "*.md" -not -name ".*" -mtime -2 -print0 | xargs -0 cp -t ${N8N}
