#!/usr/bin/env bash

VAULT=${HOME}/Vault

# find ${VAULT} \
#     \( -path '*/3. Review' -o -path '*/Daily Notes' -o -path '*/.git' -o -path '*/.obsidian' \) \
#     -prune \
#     -o \
#     -type f \
#     -name "*.md" \
#     -not -name ".*" \
#     -mtime -2 -print


OUT="${HOME}/review/dump"
mkdir -p $OUT
find ${VAULT} \( -path '*/3. Review' -o -path '*/Daily Notes' -o -path '*/.git' -o -path '*/.obsidian' \) -prune -o -type f -name "*.md" -not -name ".*" -mtime -2 -print0 | xargs -0 cp -t ${OUT}
