#!/usr/bin/env bash

VAULT=${HOME}/Vault

# find ${VAULT} \
#     \( -path '*/3. Review' -o -path '*/Daily Notes' -o -path '*/.git' -o -path '*/.obsidian' \) \
#     -prune \
#     -o \
#     -type f \
#     -name "*.md" \
#     -not -name ".*" \
#     -mtime -2 -print


OUT="/run/user/1003/gvfs/google-drive:host=hc.fm.usp.br,user=fernando.marcon/0AFvyNXMWdL2AUk9PVA/1q90jMUPhM400orLJ1_TpOkalSuLsL1_Y"
# mkdir -p $N8N
find ${VAULT} \( -path '*/3. Review' -o -path '*/Daily Notes' -o -path '*/.git' -o -path '*/.obsidian' \) -prune -o -type f -name "*.md" -not -name ".*" -mtime -2 -print0 | xargs -0 cp -t ${OUT}
